@startuml 
allow_mixing
left to right direction
package "4"{
class WebService
class LoggingRequestInterfaceImpl
interface LoggingRequestInterface

}
package "2"{
class Logging
class LoggingHandleRequest

}
"4" ..> "2":HTTP:logtrace
@enduml