@startuml 
allow_mixing
left to right direction
package "4"{
class WebService
class CursoRequestInterfaceImpl
interface CursoRequestInterface

}
package "6"{
class Curso
class CursoHandleRequest

}
"4" ..> "6":HTTP:getPk_id_curso
@enduml