@startuml 
allow_mixing
left to right direction
package "1"{
class ConsultaInscripcionController
class ProfesorRepRequestInterfaceImpl
interface ProfesorRepRequestInterface

}
package "0"{
class ProfesorRep
class ProfesorRepHandleRequest

}
"1" ..> "0":HTTP:findByName
@enduml