@startuml 
allow_mixing
left to right direction
package "2"{
class CertificadoMasivoController
class ProfesorRepRequestInterfaceImpl
interface ProfesorRepRequestInterface

}
package "0"{
class ProfesorRep
class ProfesorRepHandleRequest

}
"2" ..> "0":HTTP:findByCorreo
@enduml