@startuml 
allow_mixing
left to right direction
package "2"{
class ClienteCertificadoController
interface CursoRepDTOInterface
entity CursoRepDTO
class CursoRepRequestInterfaceImpl
interface CursoRepRequestInterface

}
package "6"{
class CursoRep
class CursoRepHandleRequest

}
"2" --x "6":methodInvocation,variableType
"2" ..> "6":HTTP:findAll
@enduml