@startuml 
allow_mixing
left to right direction
package "4"{
class WebService
interface InscripcionRepDTOInterface
entity InscripcionRepDTO
class InscripcionRepRequestInterfaceImpl
interface InscripcionRepRequestInterface

}
package "1"{
class InscripcionRep
class InscripcionRepHandleRequest

}
"4" --x "1":methodInvocation,variableType
"4" ..> "1":HTTP:saveI
@enduml