@startuml 
allow_mixing
left to right direction
package "6"{
class ModificarCursos
class LoggingRequestInterfaceImpl
interface LoggingRequestInterface

}
package "2"{
class Logging
class LoggingHandleRequest

}
"6" ..> "2":HTTP:setTrace
@enduml