@startuml 
allow_mixing
left to right direction
package "1"{
class ModificarInscripcion
class ProfesorRequestInterfaceImpl
interface ProfesorRequestInterface

}
package "0"{
class Profesor
class ProfesorHandleRequest

}
"1" ..> "0":HTTP:getRfc
@enduml