@startuml 
allow_mixing
left to right direction
package "0"{
class ConsultaProfesorController
interface GrupoRepDTOInterface
entity GrupoRepDTO
class GrupoRepRequestInterfaceImpl
interface GrupoRepRequestInterface

}
package "3"{
class GrupoRep
class GrupoRepHandleRequest

}
"0" --x "3":methodInvocation,variableType
"0" ..> "3":HTTP:findByIdAsesor
@enduml