@startuml 
allow_mixing
left to right direction
package "2"{
entity Certificado
interface CertificadoInterface

}
package "6"{
entity Curso
interface CursoInterface

}
"2" --x "6":ManyToOne
"2" ..> "6"
@enduml