@startuml 
allow_mixing
left to right direction
package "2"{
class CertificadoMasivoController
class CursoRequestInterfaceImpl
interface CursoRequestInterface

}
package "6"{
class Curso
class CursoHandleRequest

}
"2" ..> "6":HTTP:getGrupos
@enduml