@startuml 
allow_mixing
left to right direction
package "1"{
class ConsultaInscripcionController
class CursoRepRequestInterfaceImpl
interface CursoRepRequestInterface

}
package "6"{
class CursoRep
class CursoRepHandleRequest

}
"1" ..> "6":HTTP:findByParams
@enduml