@startuml 
allow_mixing
left to right direction
package "3"{
class GrupoController
class LoggingRequestInterfaceImpl
interface LoggingRequestInterface

}
package "2"{
class Logging
class LoggingHandleRequest

}
"3" ..> "2":HTTP:setTrace
@enduml