@startuml 
allow_mixing
left to right direction
package "1"{
class InscripcionesController
class GrupoRepRequestInterfaceImpl
interface GrupoRepRequestInterface

}
package "3"{
class GrupoRep
class GrupoRepHandleRequest

}
"1" ..> "3":HTTP:findAll
@enduml