@startuml 
allow_mixing
left to right direction
package "4"{
class WebService
class GrupoRepRequestInterfaceImpl
interface GrupoRepRequestInterface

}
package "3"{
class GrupoRep
class GrupoRepHandleRequest

}
"4" ..> "3":HTTP:findByClaveGrupoIdCurso
@enduml