@startuml
folder "Monolith" {
  folder "Microservice 1"{

  }
folder "Microservice 2"{
    
  }
  folder "Microservice 3"{
    
  }
  folder "Microservice 4"{
    
  }
  folder "Microservice 5"{
    
  }
  folder "Microservice 6"{
    
  }
}
[Microservice 0] ..> "Microservice 1":getUnsern
@enduml