@startuml 
allow_mixing
left to right direction
package "2"{
class EmployeeServiceImpl
interface GroupRoleServiceDTOInterface
entity GroupRoleServiceDTO
class GroupRoleServiceRequestInterfaceImpl
interface GroupRoleServiceRequestInterface

}
package "5"{
class GroupRoleService
class GroupRoleServiceHandleRequest

}
"2" --x "5":methodInvocation,variableType
"2" ..> "5":HTTP:findByGroupName
@enduml