@startuml 
allow_mixing
left to right direction
package "14"{
class GuestController
class ExtjsPageRequestRequestInterfaceImpl
interface ExtjsPageRequestRequestInterface

}
package "10"{
class ExtjsPageRequest
class ExtjsPageRequestHandleRequest

}
"14" ..> "10":HTTP:setSort
@enduml