@startuml 
allow_mixing
left to right direction
package "10"{
class InController
class InStorageRequestInterfaceImpl
interface InStorageRequestInterface

}
package "4"{
class InStorage
class InStorageHandleRequest

}
"10" ..> "4":HTTP:getInStorageDate
@enduml