@startuml 
allow_mixing
left to right direction
package "7"{
class workServiceImpl
class EmployeeServiceRequestInterfaceImpl
interface EmployeeServiceRequestInterface

}
package "2"{
class EmployeeService
class EmployeeServiceHandleRequest

}
"7" ..> "2":HTTP:findByUserName
@enduml