@startuml 
allow_mixing
left to right direction
package "8"{
class LeaveController
class EmployeeRequestInterfaceImpl
interface EmployeeRequestInterface

}
package "2"{
class Employee
class EmployeeHandleRequest

}
"8" ..> "2":HTTP:getDepartmentes
@enduml