@startuml 
allow_mixing
left to right direction
package "10"{
class InSendController
class EmployeeServiceRequestInterfaceImpl
interface EmployeeServiceRequestInterface

}
package "2"{
class EmployeeService
class EmployeeServiceHandleRequest

}
"10" ..> "2":HTTP:findByUserName
@enduml