@startuml 
allow_mixing
left to right direction
package "1"{
class BcardController
class BeanUtilsRequestInterfaceImpl
interface BeanUtilsRequestInterface

}
package "3"{
class BeanUtils
class BeanUtilsHandleRequest

}
"1" ..> "3":HTTP:copyProperties
@enduml