@startuml 
allow_mixing
left to right direction
package "0"{
class RoomCleanController
class SessionUtilRequestInterfaceImpl
interface SessionUtilRequestInterface

}
package "2"{
class SessionUtil
class SessionUtilHandleRequest

}
"0" ..> "2":HTTP:getUserName
@enduml