@startuml 
allow_mixing
left to right direction
package "6"{
class TravelServiceImpl
class EmployeeServiceRequestInterfaceImpl
interface EmployeeServiceRequestInterface

}
package "2"{
class EmployeeService
class EmployeeServiceHandleRequest

}
"6" ..> "2":HTTP:findByUserName
@enduml