@startuml 
allow_mixing
left to right direction
package "8"{
class LeaveController
class SessionUtilRequestInterfaceImpl
interface SessionUtilRequestInterface

}
package "2"{
class SessionUtil
class SessionUtilHandleRequest

}
"8" ..> "2":HTTP:getUserName
@enduml