@startuml 
allow_mixing
left to right direction
package "7"{
class workServiceImpl
interface SchedulEventServiceDTOInterface
entity SchedulEventServiceDTO
class SchedulEventServiceRequestInterfaceImpl
interface SchedulEventServiceRequestInterface

}
package "9"{
class SchedulEventService
class SchedulEventServiceHandleRequest

}
"7" --x "9":methodInvocation,variableType
"7" ..> "9":HTTP:findByDTO
@enduml