@startuml 
allow_mixing
left to right direction
package "8"{
class LeaveService
class IWorkflowServiceRequestInterfaceImpl
interface IWorkflowServiceRequestInterface

}
package "2"{
class IWorkflowService
class IWorkflowServiceHandleRequest

}
"8" ..> "2":HTTP:startWorkflow
@enduml