@startuml 
allow_mixing
left to right direction
package "4"{
class InStorageController
interface WorkflowVariableDTOInterface
entity WorkflowVariableDTO
class WorkflowVariableRequestInterfaceImpl
interface WorkflowVariableRequestInterface

}
package "1"{
class WorkflowVariable
class WorkflowVariableHandleRequest

}
"4" --x "1":methodInvocation,methodVariable
"4" ..> "1":HTTP:getVariableMap
@enduml