@startuml 
allow_mixing
left to right direction
package "6"{
class TravelServiceImpl
class DepartmentRequestInterfaceImpl
interface DepartmentRequestInterface

}
package "3"{
class Department
class DepartmentHandleRequest

}
"6" ..> "3":HTTP:getDeptName
@enduml