@startuml 
allow_mixing
left to right direction
package "4"{
class InStorageService
class WorkflowDTORequestInterfaceImpl
interface WorkflowDTORequestInterface

}
package "2"{
class WorkflowDTO
class WorkflowDTOHandleRequest

}
"4" ..> "2":HTTP:getBusinessKey
@enduml