@startuml 
allow_mixing
left to right direction
package "11"{
class RoomOrderService
interface EmployeeDaoDTOInterface
entity EmployeeDaoDTO
class EmployeeDaoRequestInterfaceImpl
interface EmployeeDaoRequestInterface

}
package "2"{
class EmployeeDao
class EmployeeDaoHandleRequest

}
"11" --x "2":methodInvocation,variableType
"11" ..> "2":HTTP:findByUserName
@enduml