@startuml 
allow_mixing
left to right direction
package "3"{
class IDeptService
class EmployeeServiceRequestInterfaceImpl
interface EmployeeServiceRequestInterface

}
package "2"{
class EmployeeService
class EmployeeServiceHandleRequest

}
"3" ..> "2":HTTP:findByEmpNameAndEmpNo
@enduml