@startuml 
allow_mixing
left to right direction
package "8"{
class LeaveService
class WorkflowDTORequestInterfaceImpl
interface WorkflowDTORequestInterface

}
package "2"{
class WorkflowDTO
class WorkflowDTOHandleRequest

}
"8" ..> "2":HTTP:getBusinessKey
@enduml