@startuml 
allow_mixing
left to right direction
package "5"{
class GroupRoleImpl
class DeptServiceRequestInterfaceImpl
interface DeptServiceRequestInterface

}
package "3"{
class DeptService
class DeptServiceHandleRequest

}
"5" ..> "3":HTTP:findByDeptName
@enduml