@startuml 
allow_mixing
left to right direction
package "6"{
class TravelController
class BeanUtilsRequestInterfaceImpl
interface BeanUtilsRequestInterface

}
package "3"{
class BeanUtils
class BeanUtilsHandleRequest

}
"6" ..> "3":HTTP:copyProperties
@enduml