@startuml 
allow_mixing
left to right direction
package "3"{
class DeptController
class ExtjsPageRequestRequestInterfaceImpl
interface ExtjsPageRequestRequestInterface

}
package "10"{
class ExtjsPageRequest
class ExtjsPageRequestHandleRequest

}
"3" ..> "10":HTTP:getPageable
@enduml