@startuml 
allow_mixing
left to right direction
package "4"{
class InStorageController
class ExtjsPageRequestRequestInterfaceImpl
interface ExtjsPageRequestRequestInterface

}
package "10"{
class ExtjsPageRequest
class ExtjsPageRequestHandleRequest

}
"4" ..> "10":HTTP:getPageable
@enduml