@startuml 
allow_mixing
left to right direction
package "7"{
class workServiceImpl
class EmployeeRequestInterfaceImpl
interface EmployeeRequestInterface

}
package "2"{
class Employee
class EmployeeHandleRequest

}
"7" ..> "2":HTTP:getEmpNo
@enduml