@startuml 
allow_mixing
left to right direction
package "0"{
class RoomController
interface IGuestServiceDTOInterface
entity IGuestServiceDTO
class IGuestServiceRequestInterfaceImpl
interface IGuestServiceRequestInterface

}
package "14"{
class IGuestService
class IGuestServiceHandleRequest

}
"0" --x "14":methodInvocation,variableType
"0" ..> "14":HTTP:findGuestByIdCard
@enduml