@startuml 
allow_mixing
left to right direction
package "1"{
class BcardController
class ExtjsPageRequestRequestInterfaceImpl
interface ExtjsPageRequestRequestInterface

}
package "10"{
class ExtjsPageRequest
class ExtjsPageRequestHandleRequest

}
"1" ..> "10":HTTP:getPageable
@enduml