@startuml 
allow_mixing
left to right direction
package "1"{
class BcardController
class SessionUtilRequestInterfaceImpl
interface SessionUtilRequestInterface

}
package "2"{
class SessionUtil
class SessionUtilHandleRequest

}
"1" ..> "2":HTTP:getUserName
@enduml