@startuml 
allow_mixing
left to right direction
package "7"{
class workController
interface ExtjsPageRequestDTOInterface
entity ExtjsPageRequestDTO
class ExtjsPageRequestRequestInterfaceImpl
interface ExtjsPageRequestRequestInterface

}
package "10"{
class ExtjsPageRequest
class ExtjsPageRequestHandleRequest

}
"7" --x "10":methodInvocation,methodVariable
"7" ..> "10":HTTP:getPageable
@enduml