@startuml 
allow_mixing
left to right direction
package "0"{
class RoomCleanController
class OutStorageRequestInterfaceImpl
interface OutStorageRequestInterface

}
package "10"{
class OutStorage
class OutStorageHandleRequest

}
"0" ..> "10":HTTP:getOutDetailed
@enduml