@startuml 
allow_mixing
left to right direction
package "7"{
class workServiceImpl
class DepartmentRequestInterfaceImpl
interface DepartmentRequestInterface

}
package "3"{
class Department
class DepartmentHandleRequest

}
"7" ..> "3":HTTP:getDeptName
@enduml