@startuml 
allow_mixing
left to right direction
package "1"{
class BcardController
class EmployeeServiceRequestInterfaceImpl
interface EmployeeServiceRequestInterface

}
package "2"{
class EmployeeService
class EmployeeServiceHandleRequest

}
"1" ..> "2":HTTP:findByUserName
@enduml