@startuml 
allow_mixing
left to right direction
package "6"{
class TravelController
class SessionUtilRequestInterfaceImpl
interface SessionUtilRequestInterface

}
package "2"{
class SessionUtil
class SessionUtilHandleRequest

}
"6" ..> "2":HTTP:getUserName
@enduml