@startuml 
allow_mixing
left to right direction
package "1"{
class BcardServiceImpl
class IWorkflowServiceRequestInterfaceImpl
interface IWorkflowServiceRequestInterface

}
package "2"{
class IWorkflowService
class IWorkflowServiceHandleRequest

}
"1" ..> "2":HTTP:startWorkflow
@enduml