@startuml 
allow_mixing
left to right direction
package "8"{
class LeaveController
interface ExtjsPageRequestDTOInterface
entity ExtjsPageRequestDTO
class ExtjsPageRequestRequestInterfaceImpl
interface ExtjsPageRequestRequestInterface

}
package "10"{
class ExtjsPageRequest
class ExtjsPageRequestHandleRequest

}
"8" --x "10":methodInvocation,methodVariable
"8" ..> "10":HTTP:getPageable
@enduml