@startuml 
allow_mixing
left to right direction
package "11"{
class RoomOrderService
class EmployeeDaoRequestInterfaceImpl
interface EmployeeDaoRequestInterface

}
package "2"{
class EmployeeDao
class EmployeeDaoHandleRequest

}
"11" ..> "2":HTTP:findByUserName
@enduml