@startuml 
allow_mixing
left to right direction
package "5"{
class GroupController
class BeanUtilsRequestInterfaceImpl
interface BeanUtilsRequestInterface

}
package "3"{
class BeanUtils
class BeanUtilsHandleRequest

}
"5" ..> "3":HTTP:copyProperties
@enduml