@startuml 
allow_mixing
left to right direction
package "0"{
class RoomCleanService
interface ExtjsPageRequestDTOInterface
class ExtjsPageRequestRequestInterfaceImpl
interface ExtjsPageRequestRequestInterface

}
package "10"{
class ExtjsPageRequest
class ExtjsPageRequestHandleRequest

}
"0" --x "10":methodInvocation,methodVariable
"0" ..> "10":HTTP:getPageable
@enduml