@startuml 
allow_mixing
left to right direction
package "6"{
class TravelController
class EmployeeRequestInterfaceImpl
interface EmployeeRequestInterface

}
package "2"{
class Employee
class EmployeeHandleRequest

}
"6" ..> "2":HTTP:getUserName
@enduml