@startuml 
allow_mixing
left to right direction
package "2"{
class EmployeeController
class DeptServiceRequestInterfaceImpl
interface DeptServiceRequestInterface

}
package "3"{
class DeptService
class DeptServiceHandleRequest

}
"2" --x "3":methodInvocation,variableType
"2" ..> "3":HTTP:findByDeptName
@enduml