@startuml 
allow_mixing
left to right direction
package "0"{
class RoomCleanController
class StockRequestInterfaceImpl
interface StockRequestInterface

}
package "10"{
class Stock
class StockHandleRequest

}
"0" ..> "10":HTTP:getAmount
@enduml