@startuml 
allow_mixing
left to right direction
package "1"{
class BcardServiceImpl
class EmployeeRequestInterfaceImpl
interface EmployeeRequestInterface

}
package "2"{
class Employee
class EmployeeHandleRequest

}
"1" ..> "2":HTTP:getEmpName
@enduml