@startuml 
allow_mixing
left to right direction
package "0"{
class RoomCleanService
class ExtjsPageRequestRequestInterfaceImpl
interface ExtjsPageRequestRequestInterface

}
package "10"{
class ExtjsPageRequest
class ExtjsPageRequestHandleRequest

}
"0" ..> "10":HTTP:getPageable
@enduml