@startuml 
allow_mixing
left to right direction
package "9"{
class SchedulEventServiceImpl
class DepartmentRequestInterfaceImpl
interface DepartmentRequestInterface

}
package "3"{
class Department
class DepartmentHandleRequest

}
"9" ..> "3":HTTP:getDeptName
@enduml