@startuml 
allow_mixing
left to right direction
package "2"{
class EmployeeServiceImpl
class GroupRoleServiceRequestInterfaceImpl
interface GroupRoleServiceRequestInterface

}
package "5"{
class GroupRoleService
class GroupRoleServiceHandleRequest

}
"2" ..> "5":HTTP:findByGroupName
@enduml