@startuml 
allow_mixing
left to right direction
package "0"{
class RoomCleanController
class EmployeeServiceRequestInterfaceImpl
interface EmployeeServiceRequestInterface

}
package "2"{
class EmployeeService
class EmployeeServiceHandleRequest

}
"0" ..> "2":HTTP:findByUserName
@enduml