@startuml
package "6"{
class JwtResponse
class MailService
class AuthController
class Role
class RoleRepository
class LoginForm
class SignUpForm
class JwtProviderRequestInterfaceImpl
class MailServiceHandleRequest
class UserRequestInterfaceImpl
class UserRepositoryRequestInterfaceImpl
class RoleRepositoryHandleRequest
interface JwtProviderDTOInterface
interface JwtProviderRequestInterface
interface RoleInterface
interface UserRequestInterface
interface UserRepositoryDTOInterface
interface UserRepositoryRequestInterface
entity JwtProviderDTO
entity UserRepositoryDTO
entity ReservationDTO
}
package "0"{
class WebSecurityConfiguration
class JwtAuthEntryPoint
class JwtAuthTokenFilter
class JwtProvider
class UserDetailsServiceImplRequestInterfaceImpl
class UserPrincipleRequestInterfaceImpl
class JwtProviderHandleRequest
interface UserDetailsServiceImplDTOInterface
interface UserDetailsServiceImplRequestInterface
interface UserPrincipleRequestInterface
entity UserDetailsServiceImplDTO
}
package "4"{
class Dish
class RestaurantServerApplication
class DishRepository
class DishService
class DishController
class UserRepositoryRequestInterfaceImpl
class DishHandleRequest
class RTableRepositoryRequestInterfaceImpl
class RoleRepositoryRequestInterfaceImpl
interface UserRepositoryDTOInterface
interface UserRepositoryRequestInterface
interface DishInterface
interface RTableRepositoryDTOInterface
interface RTableRepositoryRequestInterface
interface RoleRepositoryDTOInterface
interface RoleRepositoryRequestInterface
entity UserRepositoryDTO
entity RTableRepositoryDTO
entity RoleRepositoryDTO
}
package "1"{
class UserDetailsServiceImpl
class UserRepository
class User
class UserPrinciple
class UserService
class UserController
class UserDetailsServiceImplHandleRequest
class UserPrincipleHandleRequest
class MailServiceRequestInterfaceImpl
class UserRepositoryHandleRequest
class UserServiceHandleRequest
class UserHandleRequest
interface UserInterface
interface MailServiceDTOInterface
interface MailServiceRequestInterface
entity ReservationDTO
entity RoleDTO
entity MailServiceDTO
}
package "5"{
class ReservationRepository
class Reservation
class ReservationService
class ReservationController
class UserServiceRequestInterfaceImpl
class UserRequestInterfaceImpl
class RTableServiceRequestInterfaceImpl
class RTableRequestInterfaceImpl
class MailServiceRequestInterfaceImpl
interface ReservationInterface
interface UserServiceDTOInterface
interface UserServiceRequestInterface
interface UserRequestInterface
interface RTableServiceDTOInterface
interface RTableServiceRequestInterface
interface RTableRequestInterface
interface MailServiceDTOInterface
interface MailServiceRequestInterface
entity UserServiceDTO
entity RTableServiceDTO
entity MailServiceDTO
}
@enduml