@startuml
package "1"{
class Inscripcion
class ConsultaInscripcionController
class ProcessorInscripcion
class InscripcionesController
class ModificarInscripcion
class InscripcionRep
class InscripcionDto
class ProfesorRepRequestInterfaceImpl
class ProfesorRequestInterfaceImpl
class Grado_profesorRequestInterfaceImpl
class GeneroRequestInterfaceImpl
class TurnoRequestInterfaceImpl
class GrupoRepRequestInterfaceImpl
class GrupoRequestInterfaceImpl
class CursoRepRequestInterfaceImpl
class CursoRequestInterfaceImpl
class CertificadoRepRequestInterfaceImpl
class CertificadoRequestInterfaceImpl
class LoggingRequestInterfaceImpl
class InscripcionHandleRequest
class InscripcionRepHandleRequest
interface InscripcionInterface
interface ProfesorRepDTOInterface
interface ProfesorRepRequestInterface
interface ProfesorRequestInterface
interface Grado_profesorRequestInterface
interface GeneroRequestInterface
interface TurnoRequestInterface
interface GrupoRepDTOInterface
interface GrupoRepRequestInterface
interface GrupoRequestInterface
interface CursoRepDTOInterface
interface CursoRepRequestInterface
interface CursoRequestInterface
interface CertificadoRepDTOInterface
interface CertificadoRepRequestInterface
interface CertificadoRequestInterface
interface LoggingDTOInterface
interface LoggingRequestInterface
class ProfesorDTO
class ProfesorRepDTO
class GeneroRepDTO
class EstadoRepDTO
class Grado_profesorRepDTO
class TurnoRepDTO
class GrupoDTO
class GrupoRepDTO
class CursoRepDTO
class Tipo_cursoRepDTO
class CertificadoRepDTO
class LoggingDTO
}
package "0"{
class ProfesorRep
class Profesor
class Grado_profesor
class Genero
class Turno
class ProfesorRep
class ProfesorRep
class Profesor
class ProfesorRep
class Profesor
}
package "7"{
}
package "Monolith" {
package "2"{
class CertificadoRep
class Certificado
class Logging
class Logging
class CertificadoMasivoController
}
package "3"{
class GrupoRep
class Grupo
class GrupoRep
class GrupoRep
class Grupo
class GrupoRep
class Grupo
}
package "4"{
class WebService
}
package "5"{
}
package "6"{
class CursoRep
class Curso
class CursoRep
}
package "8"{
}
}
"1"..>"0":ProfesorRep:findByName (HTTP)
"1"..>"0":Profesor:getFk_id_grado_profesor (HTTP)
"1"..>"0":Grado_profesor:getPk_id_grado_profesor (HTTP)
"1"..>"0":Genero:getPk_id_genero (HTTP)
"1"..>"0":Turno:getPk_id_turno (HTTP)
"1"..>"0":ProfesorRep:findByRfc (HTTP)
"1"..>"0":ProfesorRep:findAll (HTTP)
"1"..>"0":Profesor:getRfc (HTTP)
"1"..>"0":ProfesorRep:findAll (HTTP)
"1"..>"0":Profesor:getRfc (HTTP)
"1"..>"3":GrupoRep:findByClave (HTTP)
"1"..>"3":Grupo:getFk_id_curso (HTTP)
"1"..>"3":GrupoRep:findByClaveGrupoIdCurso (HTTP)
"1"..>"3":GrupoRep:findAll (HTTP)
"1"..>"3":Grupo:getClave (HTTP)
"1"..>"3":GrupoRep:findAll (HTTP)
"1"..>"3":Grupo:getClave (HTTP)
"1"..>"6":CursoRep:findByParams (HTTP)
"1"..>"6":Curso:getPk_id_curso (HTTP)
"1"..>"6":CursoRep:findByNombre (HTTP)
"1"..>"2":CertificadoRep:findCertificado (HTTP)
"1"..>"2":Certificado:getPk_id_certificado (HTTP)
"1"..>"2":Logging:setTrace (HTTP)
"1"..>"2":Logging:setTrace (HTTP)
"2"..>"1":Inscripcion:getFk_id_grupo (HTTP)
"4"..>"1":InscripcionRep:saveI (HTTP)
@enduml