@startuml
package "3"{
class Grupo
class BatchController
class ProcessorGrupo
class GrupoController
class ModificarGrupos
class GrupoRep
class ConsultaGrupoController
class ReaderGrupo
class GrupoDto
class GrupoRepHandleRequest
class ProfesorRepRequestInterfaceImpl
class ProfesorRequestInterfaceImpl
class GrupoHandleRequest
class CursoRepRequestInterfaceImpl
class CursoRequestInterfaceImpl
class LoggingRequestInterfaceImpl
interface GrupoInterface
interface ProfesorRepDTOInterface
interface ProfesorRepRequestInterface
interface ProfesorRequestInterface
interface CursoRepDTOInterface
interface CursoRepRequestInterface
interface CursoRequestInterface
interface LoggingDTOInterface
interface LoggingRequestInterface
class SendMailServiceDTO
class ProfesorDTO
class ProfesorRepDTO
class GeneroRepDTO
class EstadoRepDTO
class Grado_profesorRepDTO
class TurnoRepDTO
class InscripcionDTO
class InscripcionRepDTO
class CursoDTO
class CursoRepDTO
class Tipo_cursoRepDTO
class CertificadoDTO
class LoggingDTO
}
package "0"{
class ProfesorRep
class Profesor
class ProfesorRep
class ProfesorRep
class Profesor
class Profesor
class ProfesorRep
class ConsultaProfesorController
}
package "1"{
class ConsultaInscripcionController
class ConsultaInscripcionController
class ProcessorInscripcion
class InscripcionesController
class InscripcionesController
class ModificarInscripcion
class ModificarInscripcion
}
package "2"{
class Logging
class Logging
class ClienteCertificadoController
class ClienteCertificadoController
class CertificadoMasivoController
}
package "5"{
}
package "6"{
class CursoRep
class CursoRep
class CursoRep
class Curso
class Curso
class CursoRep
class Curso
}
package "7"{
}
package "Monolith" {
package "4"{
class WebService
class WebService
}
package "8"{
}
}
"3"..>"0":ProfesorRep:loadAllProfesor(HTTP)
"3"..>"0":Profesor:getNombre(HTTP)
"3"..>"0":ProfesorRep:findByRfc(HTTP)
"3"..>"0":ProfesorRep:findAll(HTTP)
"3"..>"0":Profesor:getRfc(HTTP)
"3"..>"0":Profesor:getRfc(HTTP)
"3"..>"0":ProfesorRep:findAll(HTTP)
"3"..>"6":CursoRep:loadAllCursos(HTTP)
"3"..>"6":CursoRep:findByNombre(HTTP)
"3"..>"6":CursoRep:findAll(HTTP)
"3"..>"6":Curso:getClave(HTTP)
"3"..>"6":Curso:getClave(HTTP)
"3"..>"6":CursoRep:findAll(HTTP)
"3"..>"6":Curso:getClave(HTTP)
"3"..>"2":Logging:setTrace(HTTP)
"3"..>"2":Logging:setTrace(HTTP)
"0"..>"3":GrupoRep:findByIdAsesor (HTTP)
"1"..>"3":GrupoRep:findByClave (HTTP)
"1"..>"3":Grupo:getFk_id_curso (HTTP)
"1"..>"3":GrupoRep:findByClaveGrupoIdCurso (HTTP)
"1"..>"3":GrupoRep:findAll (HTTP)
"1"..>"3":Grupo:getClave (HTTP)
"1"..>"3":GrupoRep:findAll (HTTP)
"1"..>"3":Grupo:getClave (HTTP)
"2"..>"3":Grupo:getClave (HTTP)
"2"..>"3":GrupoRep:findAll (HTTP)
"2"..>"3":Grupo:getClave (HTTP)
"4"..>"3":GrupoRep:findByClaveGrupoIdCurso (HTTP)
"4"..>"3":Grupo:getPk_id_grupo (HTTP)
@enduml