@startuml
package "12"{
class SalaryService
class SalaryOrder
class SalaryController
class ISalaryService
class SalaryOrderDTO
class SalaryOrderQueryDTO
class SalaryOrderRepository
class DepartmentRequestInterfaceImpl
class ExtjsPageRequestRequestInterfaceImpl
class EmployeeRequestInterfaceImpl
class SalaryOrderRepositoryHandleRequest
interface DepartmentRequestInterface
interface ExtjsPageRequestDTOInterface
interface ExtjsPageRequestRequestInterface
interface EmployeeRequestInterface
class ExtjsPageRequestDTO
class EmployeeDTO
}
package "1"{
}
package "3"{
class Department
}
package "4"{
}
package "5"{
}
package "9"{
}
package "10"{
class ExtjsPageRequest
}
package "11"{
}
package "13"{
}
package "16"{
}
package "Monolith" {
package "0"{
}
package "2"{
class Employee
}
package "6"{
}
package "7"{
}
package "8"{
}
package "14"{
}
package "15"{
class FinanceReportDailyService
}
}
"12"..>"3":Department:getDeptName (HTTP)
"12"..>"10":ExtjsPageRequest:getPageable (HTTP)
"12"..>"2":Employee:getEmpNo (HTTP)
"15"..>"12":SalaryOrderRepository:findSalaryByDay (HTTP)
@enduml