@startuml
package "0"{
class WebSecurityConfiguration
class JwtAuthEntryPoint
class JwtAuthTokenFilter
class JwtProvider
class UserDetailsServiceImplRequestInterfaceImpl
class UserPrincipleRequestInterfaceImpl
class JwtProviderHandleRequest
interface UserDetailsServiceImplDTOInterface
interface UserDetailsServiceImplRequestInterface
interface UserPrincipleRequestInterface
class UserDetailsServiceImplDTO
}
package "Monolith" {
package "1"{
class UserDetailsServiceImpl
class UserPrinciple
}
package "2"{
}
package "3"{
}
package "4"{
}
package "5"{
}
package "6"{
class AuthController
}
}
"0"..>"1":UserDetailsServiceImpl:loadUserByUsername (HTTP)
"0"..>"1":UserPrinciple:getUsername (HTTP)
"6"..>"0":JwtProvider:generateJwtToken (HTTP)
@enduml