@startuml
package "Monolith" {
package "0"{
class WebSecurityConfiguration
class JwtAuthEntryPoint
class JwtAuthTokenFilter
class JwtProvider
}
package "1"{
class UserDetailsServiceImpl
class UserDetailsServiceImpl
class UserPrinciple
}
package "2"{
}
package "3"{
}
package "4"{
}
package "5"{
}
package "6"{
}
}
"0"-->"1":UserDetailsServiceImpl:variableType
"0"-->"1":UserDetailsServiceImpl:methodInvocation, variableType
"0"-->"1":UserPrinciple:methodInvocation
"6"-->"0":JwtProvider:methodInvocation, variableType
@enduml