@startuml 
allow_mixing
left to right direction
package "0"{
class JwtProvider
class UserPrincipleRequestInterfaceImpl
interface UserPrincipleRequestInterface

}
package "1"{
class UserPrinciple
class UserPrincipleHandleRequest

}
"0" ..> "1":HTTP:getUsername
@enduml