@startuml 
allow_mixing
left to right direction
package "3"{
class RTableService
class BillRequestInterfaceImpl
interface BillRequestInterface

}
package "2"{
class Bill
class BillHandleRequest

}
"3" ..> "2":HTTP:getStatus
@enduml