@startuml 
allow_mixing
left to right direction
package "6"{
class AuthController
interface JwtProviderDTOInterface
entity JwtProviderDTO
class JwtProviderRequestInterfaceImpl
interface JwtProviderRequestInterface

}
package "0"{
class JwtProvider
class JwtProviderHandleRequest

}
"6" --x "0":methodInvocation,variableType
"6" ..> "0":HTTP:generateJwtToken
@enduml