@startuml 
allow_mixing
left to right direction
package "5"{
class ReservationService
class UserRequestInterfaceImpl
interface UserRequestInterface

}
package "1"{
class User
class UserHandleRequest

}
"5" ..> "1":HTTP:getMail
@enduml