@startuml 
allow_mixing
left to right direction
package "0"{
class WebSecurityConfiguration
entity UserDetailsServiceImplDTO

}
package "1"{
class UserDetailsServiceImpl

}
"0" --x "1":variableType
@enduml