@startuml 
allow_mixing
left to right direction
package "2"{
class BillController
class RTableRepositoryRequestInterfaceImpl
interface RTableRepositoryRequestInterface

}
package "3"{
class RTableRepository
class RTableRepositoryHandleRequest

}
"2" ..> "3":HTTP:findById
@enduml